# Project information

site_name: Deploy Application Backend with Node.js and Frontend with Angular
site_description: 'This is a self-paced workshop designed to explore Amazon VPC, Amazon ECS, Amazon S3 and Amazon CloudFront.'
#site_author: 'beralfon@amazon.com'
site_url: 'http://aws-msg-app.ws.kabits.com'

# Repository
#repo_name: 'aws-samples/aws-security-workshops'
repo_url: 'https://github.com/aurbac/nodejs-back-and-angular-front'

google_analytics: ['UA-55517703-6', 'aws-msg-app.ws.kabits.com']

# Copyright
copyright: '&copy; 2019 - AURBAC '

extra:
  social:
    - type: 'home'
      link: 'http://aws-msg-app.ws.kabits.com'
    - type: 'twitter'
      link: 'https://twitter.com/aurbac'

nav:
    - Home: index.md
    - Modules: 
      - Create your VPC and Application Load Balancer for backend: create-vpc-alb.md
      - Prepare your development environment: prepare-your-development-environment.md
      - Deploy a Node.js backend with Amazon ECS: deploy-backedn-with-ecs.md
      - Deploy an Angular frontend with Amazon S3 and Amazon Cloudfront: deploy-frontend-with-s3-and-cloudfront.md
theme:
  name: 'material'
  palette:
    primary: 'light-green'
    accent: 'light-green'
  logo:
    icon: 'cloud_done'
markdown_extensions:
  - codehilite:
      linenums: true
  - pymdownx.mark
  - admonition
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.magiclink
